return function(Window)
    local LatestChangelog = {
        "02/6/2026",
        "<font color='rgb(0, 255, 0)'>+ Added Keep Notifications</font>",
		"<font color='rgb(0, 255, 0)'>+ Added Rush Mode Closet to Hiding Spot ESP</font>",
    }

    local function CloneReference(Object)
        if Quan and Quan.Environment.cloneref then
            return Quan.Environment.cloneref(Object)
        else
            return Object
        end
    end

    local Services = setmetatable({}, {
        __index = function(self, Name)
            return CloneReference(game:GetService(Name))
        end
    })

    local Library = Quan.Interface.Library
    local SaveManager = Quan.Interface.SaveManager
    local ThemeManager = Quan.Interface.ThemeManager

    local Toggles = Library.Toggles
    local Options = Library.Options

    local LocalPlayer = Services.Players.LocalPlayer
    local InfoTab = Window:AddTab("Info", "user")

    local User = InfoTab:AddLeftGroupbox("User Info")

    local ImageSize = Enum.ThumbnailSize.Size420x420
    local ImageType = Enum.ThumbnailType.HeadShot

    local Content = Services.Players:GetUserThumbnailAsync(LocalPlayer.UserId, ImageType, ImageSize)

    User:AddImage("UserIcon", {
        Image = Content
    })

    User:AddLabel("ID: " .. LocalPlayer.Name, true)
    User:AddLabel("Total Executions: " .. (Quan.TotalExecutions and Quan.TotalExecutions or "N/A"), true)

    local Changelog = InfoTab:AddRightGroupbox("Changelog")
    for Index, Change in pairs(LatestChangelog) do
        Changelog:AddLabel(Change, true)
    end

    local Name, Version = Quan.Environment.identifyexecutor()
    local Executor = InfoTab:AddRightGroupbox("Executor Info")
    Executor:AddLabel("Name: " .. Name, true)
    Executor:AddLabel("Version: " .. (Version and Version or "N/A"), true)
    Executor:AddDivider()
    Executor:AddLabel("Test Result: ", true)

    for Index, Result in pairs(Quan.Environment.Results) do
		-- fix for veloshitty 💔
		Result = Result:gsub("<", "(")
		Result = Result:gsub(">", ")")
		
        Executor:AddLabel(Result, true)
    end

    local Community = InfoTab:AddLeftGroupbox("Community")
    Community:AddButton("Copy Discord Invite", function()
	    toclipboard("https://discord.gg/5jwbZcqjVF")
	    Library:Notify("Discord invite copied.")
    end)
	Community:AddButton("Copy Youtube Channel", function()
	    toclipboard("https://youtube.com/channel/UCo4LwRkDBdVKmQAwHYdLRiA")
	    Library:Notify("Youtube channel copied.")
    end)
end
